export const PATH_HOME = '/'
export const PATH_DASHBOARD =
  '/' + import.meta.env.VITE_INITIAL_ACTIVITY_ID + '/dashboard'
export const PATH_CONSOLE = 'console'
export const PATH_APPS = 'services'
export const PATH_SETTING = 'settings'
export const PATH_LOGIN = '/login'
export const PATH_MODULE_GOALS = 'goals/:module'

// external routes
export const BASE_API_PATH = import.meta.env?.VITE_APP_API_SERVICE_URL
export const API_PATH_GET_REPOSITORIES = '/repositories'
export const API_PATH_CLONE_REPOSITORY = '/repositories/clone'
export const API_PATH_GET_TAG_LIST = '/get_tags/'
export const API_PATH_CHECKOUT = '/checkout'
export const API_PATH_LOGIN = '/login'
export const API_PATH_GET_USER_MENU_OPTION = '/menu_options/'
export const API_PATH_GET_MENU_OPTIONS_WITH_PERMISSIONS =
  '/menu_options/get_with_permission'
export const API_GET_STAFF_PAGINATION = '/staff/pagination'
export const API_PATH_CREATE_UPDATE_STAFF = '/staff'
export const API_PATH_GET_USER_PAGINATION = '/user/pagination'
export const API_PATH_CREATE_UPDATE_ROLE = '/role'
export const API_PATH_GET_ROLE_PAGINATION = '/role/pagination'
export const API_PATH_CREATE_UPDATE_USER = '/user'
export const API_PATH_GET_USER = '/user/'
export const API_PATH_CHANGE_PASSWORD = '/user/change_password'
export const API_PATH_GET_MODULE_PAGINATION = '/module/pagination'
export const API_PATH_CREATE_UPDATE_MODULE = '/module'
export const API_PATH_CREATE_OR_UPDATE_MODULE_MEMBERS = '/module/members'
// goals
export const API_PATH_CREATE_GOAL = '/goal'
export const API_PATH_ASSIGN_GOAL_STAFF = '/goal/assign/staff'
export const API_PATH_ASSIGN_GOAL_MODULE = '/goal/assign/module'
export const API_PATH_POST_GOAL_PROGRESS = '/goal/progress'
export const API_PATH_GET_GOAL_SUMMARY_STAFF = '/goal/summary/staff/'
export const API_PATH_GET_GOAL_SUMMARY_MODULE = '/goal/summary/module/'
export const API_PATH_GET_GOAL_SUMMARY_MODULE_PAGINATION =
  '/goal/summary/module/pagination'
export const API_PATH_GET_GOALS_BY_MODULE = '/goal/module/'
